language: ruby
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='suzuryo@travis-ci'
    - GIT_COMMITTER_EMAIL='suzuryo@gmail.com'
    - GIT_AUTHOR_NAME='suzuryo@travis-ci'
    - GIT_AUTHOR_EMAIL='suzuryo@gmail.com'
    - secure: "d7F1+sSKivl7QsUbMbJOvKn7NISeXqQCK2PBzbfDGl6jngtw0Ds5LPvEm3PJyyG/Ab/ZmVAf0SbbttLvWexiyX6s+ZPAZoZqZZAdtEPSgbTgFslB3zMv4+D9nzaoV1zdcdfgUaLkbuyzdCCxtQTcLgq3eRJEcXJR/2XdTgPLGL8="
after_success:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
  - openssl aes-256-cbc -k "$SERVER_KEY" -in .travis/deploy_key.enc -d -a -out deploy.key
  - cp deploy.key ~/.ssh/
  - chmod 600 ~/.ssh/deploy.key
  - '[ "$TRAVIS_BRANCH" == "master" ] && bundle exec middleman deploy'
notifications:
  slack:
    secure: ga7ZatcZ8wiUH5zXyWRWDJd9WvVbG2K9SxLKezsi4bXfuGLyaHi46srQ57WmUV11YVLzVB48L9cUmekUsRlKGvqke2SMKHJCeEAhDEVqYqpTeRCB6CYgGoK0krzL3RALqZiLyYE61NWqatnObiNATJ+Emi0nGxqLYa3zX+haTvI=
