language: ruby
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='suzuryo@travis-ci'
    - GIT_COMMITTER_EMAIL='suzuryo@gmail.com'
    - GIT_AUTHOR_NAME='suzuryo@travis-ci'
    - GIT_AUTHOR_EMAIL='suzuryo@gmail.com'
before_install:
  - openssl aes-256-cbc -K $encrypted_6ab3f0658595_key -iv $encrypted_6ab3f0658595_iv -in .travis/deploy_key.enc -out deploy_key -d
after_success:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy_key\n" >> ~/.ssh/config
  - cp deploy_key ~/.ssh/
  - chmod 600 ~/.ssh/deploy_key
  - '[ "$TRAVIS_BRANCH" == "master" ] && bundle exec middleman deploy'
notifications:
  slack:
    secure: ga7ZatcZ8wiUH5zXyWRWDJd9WvVbG2K9SxLKezsi4bXfuGLyaHi46srQ57WmUV11YVLzVB48L9cUmekUsRlKGvqke2SMKHJCeEAhDEVqYqpTeRCB6CYgGoK0krzL3RALqZiLyYE61NWqatnObiNATJ+Emi0nGxqLYa3zX+haTvI=
