language: ruby
script: bundle exec middleman build
before_script:
  - bundle install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
notifications:
  slack:
    rooms:
      - iwdd:KOI2kgilXYqZzsoR9FM4nH0D
      - secure: ga7ZatcZ8wiUH5zXyWRWDJd9WvVbG2K9SxLKezsi4bXfuGLyaHi46srQ57WmUV11YVLzVB48L9cUmekUsRlKGvqke2SMKHJCeEAhDEVqYqpTeRCB6CYgGoK0krzL3RALqZiLyYE61NWqatnObiNATJ+Emi0nGxqLYa3zX+haTvI=
