language: ruby
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='suzuryo@travis-ci'
    - GIT_COMMITTER_EMAIL='suzuryo@gmail.com'
    - GIT_AUTHOR_NAME='suzuryo@travis-ci'
    - GIT_AUTHOR_EMAIL='suzuryo@gmail.com'
    - secure: RX7jVdb6k1+O2hETro91DEh/DwcYQTWJCqva9zqSyPOC7RnmpyC1LdnqaGEoBFZN154Babuz8xu/aAgm+bmohNBv1p5iuo7SyskD8qvX9xm8KGAVKvehD8Hcf00UYtCMAVe1tpVqi8f7XjinNLY3h1ZDs339QctYCE1+iRucELc=
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy'
