language: ruby
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='suzuryo@travis-ci'
    - GIT_COMMITTER_EMAIL='suzuryo@gmail.com'
    - GIT_AUTHOR_NAME='suzuryo@travis-ci'
    - GIT_AUTHOR_EMAIL='suzuryo@gmail.com'
    - secure: xix1NOMLJWJzs+RprmFaqArSMunYFzy6SakBrBBa8hRwhAJ3Ne5svciGMrHzR4qfG6SevAysYCOYiD5aV6qpL/NSWUgPAdgfAXEqjMzLUDhbGulSU7P0l/PhMwE7CKdkOTiAYh0ugwWyBMilvBIi/UC5A7FCvCC+HmlcSbmDg8k=
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy'
